name: Code checks

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@master
      - name: npm install
        run: npm install
      - name: npm test
        run: npm test
      - name: Docker build
        run: docker build .
